//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBanHangOnlineNhomNBTPQ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQUANLYBANQUANAOEntities1 : DbContext
    {
        public dbQUANLYBANQUANAOEntities1()
            : base("name=dbQUANLYBANQUANAOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbCHITIETDONHANG> tbCHITIETDONHANGs { get; set; }
        public DbSet<tbDANHMUC> tbDANHMUCs { get; set; }
        public DbSet<tbHINHANH> tbHINHANHs { get; set; }
        public DbSet<tbHOADON> tbHOADONs { get; set; }
        public DbSet<tbKHACHHANG> tbKHACHHANGs { get; set; }
        public DbSet<tbREVIEW> tbREVIEWs { get; set; }
        public DbSet<tbSANPHAM> tbSANPHAMs { get; set; }
    }
}
