//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBanHangOnlineNhomNBTPQ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQUANLYBANQUANAOEntities2 : DbContext
    {
        public dbQUANLYBANQUANAOEntities2()
            : base("name=dbQUANLYBANQUANAOEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbCHITIETDONHANG> tbCHITIETDONHANG { get; set; }
        public DbSet<tbDANHMUC> tbDANHMUC { get; set; }
        public DbSet<tbHINHANH> tbHINHANH { get; set; }
        public DbSet<tbHOADON> tbHOADON { get; set; }
        public DbSet<tbKHACHHANG> tbKHACHHANG { get; set; }
        public DbSet<tbREVIEW> tbREVIEW { get; set; }
        public DbSet<tbSANPHAM> tbSANPHAM { get; set; }
    }
}
