//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBanHangOnlineNhomNBTPQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHOADON
    {
        public tbHOADON()
        {
            this.tbCHITIETDONHANGs = new HashSet<tbCHITIETDONHANG>();
        }
    
        public int MAHOADON { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
    
        public virtual ICollection<tbCHITIETDONHANG> tbCHITIETDONHANGs { get; set; }
        public virtual tbKHACHHANG tbKHACHHANG { get; set; }
    }
}
