//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBanHangOnlineNhomNBTPQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbREVIEW
    {
        public int STT { get; set; }
        public string Name_Review { get; set; }
        public Nullable<int> rate { get; set; }
        public string Content_review { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public Nullable<int> MASANPHAM { get; set; }
    
        public virtual tbKHACHHANG tbKHACHHANG { get; set; }
        public virtual tbSANPHAM tbSANPHAM { get; set; }
    }
}
